Login

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -103,25 +103,23 @@ jobs:
     needs: e2e-tests-python
     if: success()  # Solo ejecuta si todo lo anterior pasó
     steps:
-      - name: Usar un Secret en un Comando
-        run: echo "Mi usuario es ${{ secrets.DOCKER_USERNAME }}"
-
-      - name: Password
-        run: echo "Mi contraseña es ${{ secrets.DOCKER_PASSWORD }}"
-
       - name: Checkout Code
         uses: actions/checkout@v4
 
-      - name: Log in to Docker Hub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
+      - name: Verificar secrets
+        run: |
+          echo "Verificando secrets..."
+          if [ -z "${{ secrets.DOCKER_USERNAME }}" ] || [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
+            echo "Error: Secrets no encontrados"
+            exit 1
+          fi
+
+      - name: Iniciar sesión
+        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password stdin
 
       - name: Build Docker Image
         run: docker compose up --build -d
 
       - name: Tag and Push to Docker Hub
         run: |
-          docker tag my-image-name:latest ${{ secrets.DOCKER_USERNAME }}/my-image-name:latest
           docker push ${{ secrets.DOCKER_USERNAME }}/my-image-name:latest
